class AIState;
int getNextTileValue();
void checkUserInput();
void handleDroppedTile();
void calculateGameScore();
void runAI();
void unpackState(AIState& newState);
void waitForReset();
void makeAIHand();
void makePlayerHand();
void makeBoard();
int getTileHScore();